language: php

php:
  - 5.4
  - 5.5

before_install:
 - mkdir module && cp phpunit.xml.dist phpunit.xml && composer install --dev --prefer-source

script:
 - ant

matrix:
  fast_finish: true

notifications:
  email: false
