language: php

php:
  - 5.4
  - 5.5

before_install:
 - mkdir module && cp phpunit.xml.dist phpunit.xml && composer install --dev --prefer-source
 - cp tests/config/autoload/doctrine-connection.local.php.dist tests/config/autoload/doctrine-connection.local.php
 - psql -c 'CREATE DATABASE test_qa_data;' -U postgres
 - php tests/bin/doctrine-module.php orm:schema-tool:update --force

script:
 - ant

matrix:
  fast_finish: true

notifications:
  email: false
